[[code_server]]
arch = "aarch64"
git-tree-sha1 = "d6939a94f3ade442c1630f54a44b89ab32da671b"
os = "macos"

    [[code_server.download]]
    sha256 = "ea624eedb7f90ed1c28c5da8694c665b3721c979a67241cc488a43ff4b33e272"
    url = "https://github.com/JuliaBinaryWrappers/code_server_jll.jl/releases/download/code_server-v4.99.2+0/code_server.v4.99.2.aarch64-apple-darwin.tar.gz"
[[code_server]]
arch = "aarch64"
git-tree-sha1 = "6bfd395e426d22471114adedc501f9ffc3b6ee17"
libc = "glibc"
os = "linux"

    [[code_server.download]]
    sha256 = "4fc7e91bd794e54fb7142f6aea5f0bd40397ffa2b48172426a3dd6631dfd85ea"
    url = "https://github.com/JuliaBinaryWrappers/code_server_jll.jl/releases/download/code_server-v4.99.2+0/code_server.v4.99.2.aarch64-linux-gnu.tar.gz"
[[code_server]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ce453e1bb390cb5df73cab87737aaa14939953c1"
libc = "glibc"
os = "linux"

    [[code_server.download]]
    sha256 = "e9e781701bbe0ea8b7966adb5fbc0ed8af53bbc57e8f004658582f4d68a5ab26"
    url = "https://github.com/JuliaBinaryWrappers/code_server_jll.jl/releases/download/code_server-v4.99.2+0/code_server.v4.99.2.armv7l-linux-gnueabihf.tar.gz"
[[code_server]]
arch = "x86_64"
git-tree-sha1 = "6468158ea50dfcaa67a9395c5484e7645e6b0186"
os = "macos"

    [[code_server.download]]
    sha256 = "ab63731806f34eecbb0c7ba35fd09a9d7c863682e28dfdf86ff86d560d83c75e"
    url = "https://github.com/JuliaBinaryWrappers/code_server_jll.jl/releases/download/code_server-v4.99.2+0/code_server.v4.99.2.x86_64-apple-darwin.tar.gz"
[[code_server]]
arch = "x86_64"
git-tree-sha1 = "0bfa5514d5100982ddb3e464387c67b514594734"
libc = "glibc"
os = "linux"

    [[code_server.download]]
    sha256 = "ccb07674183a070b2544a0cb699850d5460208af306b8e1bf637bcda188aec9f"
    url = "https://github.com/JuliaBinaryWrappers/code_server_jll.jl/releases/download/code_server-v4.99.2+0/code_server.v4.99.2.x86_64-linux-gnu.tar.gz"
